name: Build and Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Forza architettura AMD64
        run: export ARCHFLAGS='-arch x86_64'

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          architecture: 'x64'  # Usa AMD64
          cache: 'yarn'

      - name: Setup Python virtual environment
        run: |
          python3 -m venv venv
          source venv/bin/activate
          python3 -m pip install --upgrade pip
          python3 -m pip install setuptools
          # Installa distutils (se non disponibile)
          python3 -m pip install distutils
          python3 -m pip install gyp

      - name: Install system dependencies
        run: |
          # Assicurati che `make` e altre dipendenze siano presenti
          brew install make
          brew install python@3.13  # Installazione di Python 3.13 per compatibilità

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Build project for amd64
        run: yarn dist

      - name: Archive production artifacts
        run: |
          mkdir -p release
          cp -r dist/* release/

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: release/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
